var mongoose = require("mongoose");

mongoose.connect("mongodb://localhost:27017/studentDB");

var db = mongoose.connection;

db.once("open", function() {
  console.log("connection opened");
});

db.on("error", function(err) {
  console.log(err);
});

var Schema = mongoose.Schema;

const SchemaOptions = {
  autoCreate: false,
  capped: { size: 1048576, max: 90 },
  strict: true,
  strictQuery: true,
  _id: false,
  minimize: true,
  versionKey: true,
  timestamps: true
};

const StudentCollectionSchema = new Schema(
  {
    "ID": String,
    "Name": { type: String, required: [false] },
    "DOB":{ type:Date, default:Date.now },
    "Gender": String,
    "Color": String,
    "Eyes": String
  },
  SchemaOptions
);

//StudentCollectionSchema.set("validateBeforeSave", false);
//StudentCollectionSchema.path("Name").validate(value => value != "Unknown");

var StudentsModel = mongoose.model(
  "StudentCollection",
  StudentCollectionSchema
);

var vStdList =[{
    "ID": "1",
    "Name": "Senpai",
    "DOB":"2016-10-11T00:00:00Z",
    "Gender": "Male",
    "Class": "32",
    "Seat": "15",
    "Club": "0",
    "Persona": "1",
    "Crush": "0",
    "BreastSize": "0",
    "Strength": "0",
    "Hairstyle": "1",
    "Color": "Black",
    "Eyes": "Black",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13.01_13.375_15.5_16_17.25_99_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Hangout_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Read_Sit_Eat_Sit_Clean_Read_Shoes_Stand",
    "Info": "An average student. \n \n Average grades, average looks, average life... \n \n I'm not sure what you see in him."
  },
  {
    "ID": "2",
    "Name": "Yui Rio",
    "DOB":"1998-08-11T00:00:00Z",
    "Gender": "Male",
    "Class": "11",
    "Seat": "14",
    "Club": "1",
    "Persona": "5",
    "Crush": "0",
    "BreastSize": "0.5",
    "Strength": "0",
    "Hairstyle": "2",
    "Color": "Red",
    "Eyes": "Red",
    "EyeType": "Default",
    "Stockings": "Red",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_17.25_99_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Club_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_SocialSit_Shoes_Stand",
    "Info": ""
  },
  {
    "ID": "3",
    "Name": "Yuna Hina",
    "DOB":"1990-03-05",
    "Gender": "Male",
    "Class": "12",
    "Seat": "14",
    "Club": "1",
    "Persona": "6",
    "Crush": "0",
    "BreastSize": "0.8",
    "Strength": "0",
    "Hairstyle": "3",
    "Color": "Yellow",
    "Eyes": "Yellow",
    "EyeType": "Default",
    "Stockings": "Yellow",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_17.25_99_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Club_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_SocialSit_Shoes_Stand",
    "Info": ""
  },
  {
    "ID": "4",
    "Name": "Koharu Hinata",
    "DOB":"1950-10-15",
    "Gender": "Male",
    "Class": "21",
    "Seat": "14",
    "Club": "1",
    "Persona": "6",
    "Crush": "0",
    "BreastSize": "1.1",
    "Strength": "0",
    "Hairstyle": "4",
    "Color": "Green",
    "Eyes": "Green",
    "EyeType": "Default",
    "Stockings": "Green",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13.0001_13.375_15.5001_16_17.25_99_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Club_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_SocialSit_Shoes_Stand",
    "Info": ""
  },
  {
    "ID": "5",
    "Name": "Mei Mio",
    "DOB":"1950-02-15",
    "Gender": "Male",
    "Class": "22",
    "Seat": "14",
    "Club": "1",
    "Persona": "2",
    "Crush": "0",
    "BreastSize": "1.4",
    "Strength": "0",
    "Hairstyle": "5",
    "Color": "Blue",
    "Eyes": "Blue",
    "EyeType": "Default",
    "Stockings": "Blue",
    "Accessory": "7",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_17.25_99_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Club_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_SocialSit_Shoes_Stand",
    "Info": ""
  },
  {
    "ID": "6",
    "Name": "Saki Miyu",
    "DOB":"1952-08-25",
    "Gender": "Male",
    "Class": "31",
    "Seat": "14",
    "Club": "1",
    "Persona": "6",
    "Crush": "0",
    "BreastSize": "1.7",
    "Strength": "0",
    "Hairstyle": "6",
    "Color": "Cyan",
    "Eyes": "Cyan",
    "EyeType": "Default",
    "Stockings": "Cyan",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13.01_13.375_15.5_16_17.25_99_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Club_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_SocialSit_Shoes_Stand",
    "Info": "Kokona Haruka's best friend and closest confidant. Kokona is likely to discuss personal matters with this girl."
  },
  {
    "ID": "7",
    "Name": "Kokona Haruka",
    "DOB":"1952-12-10",
    "Gender": "Male",
    "Class": "32",
    "Seat": "14",
    "Club": "1",
    "Persona": "6",
    "Crush": "1",
    "BreastSize": "2",
    "Strength": "0",
    "Hairstyle": "7",
    "Color": "Purple",
    "Eyes": "Purple",
    "EyeType": "Default",
    "Stockings": "Purple",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13.01_13.375_15.51_16_17.25_99_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Club_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_SocialSit_Shoes_Stand",
    "Info": ""
  },
  {
    "ID": "8",
    "Name": "Haruto Yuto",
    "DOB":"1952-05-12",
    "Gender": "Male",
    "Class": "11",
    "Seat": "12",
    "Club": "0",
    "Persona": "5",
    "Crush": "0",
    "BreastSize": "0",
    "Strength": "0",
    "Hairstyle": "2",
    "Color": "Red",
    "Eyes": "Red",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "3",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_16.5_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_Shoes_Stand",
    "Info": ""
  },
  {
    "ID": "9",
    "Name": "Sota Yuki",
    "DOB":"2012-10-11",
    "Gender": "Male",
    "Class": "12",
    "Seat": "12",
    "Club": "0",
    "Persona": "6",
    "Crush": "0",
    "BreastSize": "0",
    "Strength": "0",
    "Hairstyle": "3",
    "Color": "Yellow",
    "Eyes": "Yellow",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_16.5_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_Shoes_Stand",
    "Info": ""
  },
  {
    "ID": "10",
    "Name": "Hayato Haruki",
    "DOB":"1975-08-18",
    "Gender": "Male",
    "Class": "21",
    "Seat": "12",
    "Club": "0",
    "Persona": "6",
    "Crush": "0",
    "BreastSize": "0",
    "Strength": "0",
    "Hairstyle": "4",
    "Color": "Green",
    "Eyes": "Green",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13.0002_13.375_15.5002_16_16.5_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_Shoes_Stand",
    "Info": ""
  },
  {
    "ID": "11",
    "Name": "Ryusei Koki",
    "DOB":"1947-12-29",
    "Gender": "Male",
    "Class": "22",
    "Seat": "12",
    "Club": "0",
    "Persona": "2",
    "Crush": "0",
    "BreastSize": "0",
    "Strength": "0",
    "Hairstyle": "5",
    "Color": "Blue",
    "Eyes": "Blue",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "4",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_16.5_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_Shoes_Stand",
    "Info": ""
  },
  {
    "ID": "12",
    "Name": "Sora Sosuke",
    "Gender": "Male",
    "Class": "31",
    "Seat": "12",
    "Club": "0",
    "Persona": "6",
    "Crush": "0",
    "BreastSize": "0",
    "Strength": "0",
    "Hairstyle": "6",
    "Color": "Cyan",
    "Eyes": "Cyan",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_16.5_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_Shoes_Stand",
    "Info": ""
  },
  {
    "ID": "13",
    "Name": "Riku Soma",
    "Gender": "Male",
    "Class": "32",
    "Seat": "12",
    "Club": "0",
    "Persona": "6",
    "Crush": "7",
    "BreastSize": "0",
    "Strength": "0",
    "Hairstyle": "7",
    "Color": "Purple",
    "Eyes": "Purple",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_16.25_17.5_99_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Stalk_Patrol_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Socialize_Sit_Clean_Stalk_Patrol_Shoes_Stand",
    "Info": "Comes from a rich family. He tries to hide this fact from others, but his affluent origins are very obvious because of his unusual way of speaking."
  },
  {
    "ID": "14",
    "Name": "Pippi Osu",
    "Gender": "Male",
    "Class": "11",
    "Seat": "5",
    "Club": "11",
    "Persona": "10",
    "Crush": "15",
    "BreastSize": "1",
    "Strength": "0",
    "Hairstyle": "8",
    "Color": "Pippi",
    "Eyes": "Green",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_16.5_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_Hangout_Seat_Clean_Hangout_Hangout",
    "ScheduleAction": "Stand_Stand_Game_Sit_Game_Sit_Clean_Game_Game",
    "Info": "Extremely unlikely to witness murder unless it takes place in the computer lab."
  },
  {
    "ID": "15",
    "Name": "Ryuto Ippongo",
    "Gender": "Male",
    "Class": "12",
    "Seat": "5",
    "Club": "11",
    "Persona": "10",
    "Crush": "14",
    "BreastSize": "0",
    "Strength": "0",
    "Hairstyle": "8",
    "Color": "Red",
    "Eyes": "Red",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "1",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_16.5_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_Hangout_Seat_Clean_Hangout_Hangout",
    "ScheduleAction": "Stand_Stand_Game_Sit_Game_Sit_Clean_Game_Game",
    "Info": "Secretly has a crush on Pippi Osu. Neither of them realize that they both share feelings for each other. \n \n Swears to his parents that he spends all of his free time studying."
  },
  {
    "ID": "16",
    "Name": "Midori Gurin",
    "Gender": "Male",
    "Class": "31",
    "Seat": "5",
    "Club": "11",
    "Persona": "10",
    "Crush": "0",
    "BreastSize": "1",
    "Strength": "0",
    "Hairstyle": "9",
    "Color": "Green",
    "Eyes": "Green",
    "EyeType": "Default",
    "Stockings": "ShortGreen",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_16.5_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_Hangout_Seat_Clean_Hangout_Hangout",
    "ScheduleAction": "Stand_Stand_Text_Sit_Text_Sit_Clean_Text_Text",
    "Info": "Known for irritating her classmates and teachers by constantly asking foolish questions."
  },
  {
    "ID": "17",
    "Name": "Sakyu Basu",
    "Gender": "Male",
    "Class": "21",
    "Seat": "5",
    "Club": "0",
    "Persona": "6",
    "Crush": "0",
    "BreastSize": "1.5",
    "Strength": "0",
    "Hairstyle": "10",
    "Color": "Succubus1",
    "Eyes": "Succubus1",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "3",
    "ScheduleTime": "7_7_8_13.0003_13.375_15.5003_16_16.5_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Eat_Sit_Clean_Shoes_Stand",
    "Info": "Wears contact lenses. \n \n Enjoys spending time with her younger sister. \n \n Rumored to be a succubus disguised as a high school student...but only a fool would believe something like that."
  },
  {
    "ID": "18",
    "Name": "Inkyu Basu",
    "Gender": "Male",
    "Class": "22",
    "Seat": "5",
    "Club": "0",
    "Persona": "6",
    "Crush": "0",
    "BreastSize": "1",
    "Strength": "0",
    "Hairstyle": "11",
    "Color": "Succubus2",
    "Eyes": "Succubus2",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_16.5_99",
    "ScheduleDestination": "Spawn_Locker_Hangout_Seat_LunchSpot_Seat_Clean_Locker_Exit",
    "ScheduleAction": "Stand_Stand_Socialize_Sit_Eat_Sit_Clean_Shoes_Stand",
    "Info": "Wears contact lenses. \n \n Enjoys spending time with her older sister. \n \n Rumored to be a vampire disguised as a high school student...but only a fool would believe something like that."
  },
  {
    "ID": "35",
    "Name": "Unknown",
    "Gender": "Male",
    "Class": "0",
    "Seat": "0",
    "Club": "0",
    "Persona": "0",
    "Crush": "0",
    "BreastSize": "1",
    "Strength": "0",
    "Hairstyle": "1",
    "Color": "White",
    "Eyes": "Black",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_99",
    "ScheduleDestination": "Spawn_Locker_Patrol_Seat_Patrol_Seat_Clean_Patrol",
    "ScheduleAction": "Stand_Stand_Patrol_Sit_Patrol_Sit_Clean_Patrol",
    "Info": ""
  },
  {
    "ID": "36",
    "Name": "Unknown",
    "Gender": "Male",
    "Class": "0",
    "Seat": "0",
    "Club": "0",
    "Persona": "0",
    "Crush": "0",
    "BreastSize": "1",
    "Strength": "0",
    "Hairstyle": "1",
    "Color": "White",
    "Eyes": "Black",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_99",
    "ScheduleDestination": "Spawn_Locker_Patrol_Seat_Patrol_Seat_Clean_Patrol",
    "ScheduleAction": "Stand_Stand_Patrol_Sit_Patrol_Sit_Clean_Patrol",
    "Info": ""
  },
  {
    "ID": "37",
    "Name": "Unknown",
    "Gender": "Male",
    "Class": "0",
    "Seat": "0",
    "Club": "0",
    "Persona": "0",
    "Crush": "0",
    "BreastSize": "1",
    "Strength": "0",
    "Hairstyle": "1",
    "Color": "White",
    "Eyes": "Black",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_99",
    "ScheduleDestination": "Spawn_Locker_Patrol_Seat_Patrol_Seat_Clean_Patrol",
    "ScheduleAction": "Stand_Stand_Patrol_Sit_Patrol_Sit_Clean_Patrol",
    "Info": ""
  },
  {
    "ID": "38",
    "Name": "Unknown",
    "Gender": "Male",
    "Class": "0",
    "Seat": "0",
    "Club": "0",
    "Persona": "0",
    "Crush": "0",
    "BreastSize": "1",
    "Strength": "0",
    "Hairstyle": "1",
    "Color": "White",
    "Eyes": "Black",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_99",
    "ScheduleDestination": "Spawn_Locker_Patrol_Seat_Patrol_Seat_Clean_Patrol",
    "ScheduleAction": "Stand_Stand_Patrol_Sit_Patrol_Sit_Clean_Patrol",
    "Info": ""
  },
  {
    "ID": "39",
    "Name": "Unknown",
    "Gender": "Male",
    "Class": "0",
    "Seat": "0",
    "Club": "0",
    "Persona": "0",
    "Crush": "0",
    "BreastSize": "1",
    "Strength": "0",
    "Hairstyle": "1",
    "Color": "White",
    "Eyes": "Black",
    "EyeType": "Default",
    "Stockings": "None",
    "Accessory": "0",
    "ScheduleTime": "7_7_8_13_13.375_15.5_16_99",
    "ScheduleDestination": "Spawn_Locker_Patrol_Seat_Patrol_Seat_Clean_Patrol",
    "ScheduleAction": "Stand_Stand_Patrol_Sit_Patrol_Sit_Clean_Patrol",
    "Info": ""
  }
];

StudentsModel.insertMany(vStdList, function(err, data) {
    console.log(err, data);
    mongoose.disconnect();
});